import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';

const canvas=document.querySelector('#game'), keys=new Set(); let playing=false, muted=false, progress=0, audio;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x9b5647); scene.fog=new THREE.Fog(0x9b5647,42,170);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,260); const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15;
scene.add(new THREE.HemisphereLight(0xffd0a0,0x3c2021,2.3)); const sun=new THREE.DirectionalLight(0xffbd83,4); sun.position.set(-35,55,25); sun.castShadow=true; sun.shadow.mapSize.set(1536,1536); sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=70;sun.shadow.camera.bottom=-70;scene.add(sun);
const mat=(color,rough=1)=>new THREE.MeshStandardMaterial({color,roughness:rough}); const sand=mat(0x9b543b), dark=mat(0x342326), wood=mat(0x5e3329), roof=mat(0x292026), cactus=mat(0x315143), gold=mat(0xd18b4e);
function box(n,p,s,m){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
function cone(n,p,r,h,m,seg=7){const o=new THREE.Mesh(new THREE.ConeGeometry(r,h,seg),m);o.name=n;o.position.set(...p);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
// terrain with ridged mesa silhouettes
box('terrain',[0,-1,0],[190,2,190],sand);
for(let i=0;i<16;i++){const x=-75+(i*37)%150,z=-62-(i*23)%100; cone('red mesa',[x,5,z],12+(i%4)*5,12+(i%3)*6,mat(i%2?0x6d3b34:0x774238),6);}
// distant mountains and town
for(let i=0;i<10;i++) cone('distant ridge',[-75+i*17,7,-70],16+(i%3)*4,18+(i%4)*5,mat(0x553238),6);
function building(x,z,w=7,h=4){box('Dusthaven building',[x,h/2,z],[w,h,6],wood);const r=cone('roof',[x,h+1,z],w*.72,2.8,roof,4);r.rotation.y=Math.PI/4;box('door',[x,.9,z-3.05],[1.4,2.2,.15],dark);box('window',[x-w*.25,2,z-3.08],[1.2,1.1,.12],gold);}
[[-18,-11,8,5],[-8,-13,7,4],[3,-12,8,5],[14,-10,6,4]].forEach(v=>building(...v));
box('main street',[-1,.04,-14],[48,.08,5],mat(0xb77a51));
function makeCactus(x,z){const g=new THREE.Group();const stem=new THREE.Mesh(new THREE.CylinderGeometry(.65,.8,5,8),cactus);stem.position.y=2.5;g.add(stem);for(const [sx,sy,rot] of [[1.1,2.5,-Math.PI/2],[-1,1.8,Math.PI/2]]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.4,.5,2.3,8),cactus);arm.position.set(sx,sy,0);arm.rotation.z=rot;g.add(arm);}g.position.set(x,0,z);g.traverse(o=>{o.castShadow=true});scene.add(g)}
for(let i=0;i<24;i++)makeCactus(-62+(i*29)%125,-5-(i*47)%95);
// signal fire objective
const fire=cone('signal fire',[30,.8,-62],1.6,1.5,mat(0x4b2922),6); const flame=cone('signal flame',[30,2.7,-62],1.2,3.3,new THREE.MeshBasicMaterial({color:0xff8b36}),7); flame.scale.x=.65; const fireLight=new THREE.PointLight(0xff7b38,8,22);fireLight.position.set(30,3,-62);scene.add(fireLight); for(let i=0;i<8;i++){const rock=cone('fire stone',[30+Math.cos(i)*2,.4,-62+Math.sin(i)*2],.35,.6,dark,6);}
// horse: stylized but detailed assembled 3D mesh
const horse=new THREE.Group(); horse.position.set(4,0,-2); scene.add(horse);
const horseMat=mat(0x49302a), mane=mat(0x201a20); function hbox(p,s,m=horseMat){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);o.castShadow=true;horse.add(o);return o}
const body=hbox([0,2,0],[3.8,2.1,1.25]); const neck=hbox([1.5,3.25,0],[1.1,2.7,1]); neck.rotation.z=-.28; hbox([2.25,4.4,0],[1.45,1.05,1]); hbox([1.8,4.95,0],[1.9,.18,1.5],mane); for(const x of [-1.3,-.55,.7,1.25]){const leg=hbox([x,.8,0],[.38,2.5,.42]);leg.name='horse leg'} hbox([-1.5,3.05,0],[.6,.75,1.45],mane); hbox([0,3.35,0],[.25,.25,1.45],mat(0xb87342));
const rider=new THREE.Group(); horse.add(rider); hbox([-.25,3.35,0],[.9,1.35,.75],mat(0x263244)); const head=hbox([-.25,4.35,0],[.65,.65,.65],mat(0xb87551)); hbox([-.25,4.72,0],[1.3,.2,.9],roof);
const hero={x:0,z:5,heading:0}; const clock=new THREE.Clock(); let elapsed=0;
function dust(){const geo=new THREE.BufferGeometry(),a=[];for(let i=0;i<420;i++)a.push((Math.random()-.5)*110,Math.random()*1.6-.1,(Math.random()-.5)*110);geo.setAttribute('position',new THREE.Float32BufferAttribute(a,3));const p=new THREE.Points(geo,new THREE.PointsMaterial({color:0xd28c62,size:.11,transparent:true,opacity:.32}));scene.add(p);return p} const particles=dust();
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)} addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='e'&&playing)interact()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function interact(){const d=Math.hypot(hero.x-horse.position.x,hero.z-horse.position.z);if(d<6){progress=Math.min(1,progress+.25);toast(progress>=1?'The letter is found. A new trail opens east.':'The saddle creaks. The frontier is listening.')}else if(Math.hypot(hero.x-30,hero.z+62)<9){progress=1;toast('Signal fire lit. Dusthaven will remember your name.')}else toast('Nothing but wind and red stone.');}
function toast(s){const el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3600);if(!muted)sfx(220,.12)}
function sfx(freq,dur){try{const A=window.AudioContext||window.webkitAudioContext;if(!A||muted)return;audio||(audio=new A());if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.035,audio.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur+.03)}catch{}}
function update(dt){if(!playing)return;const gallop=keys.has('shift')||keys.has(' '),speed=(gallop?10:5)*dt;let dx=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));let dz=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));if(dx||dz){const len=Math.hypot(dx,dz);dx/=len;dz/=len;hero.x=Math.max(-80,Math.min(80,hero.x+dx*speed));hero.z=Math.max(-88,Math.min(30,hero.z+dz*speed));hero.heading=Math.atan2(dx,dz);horse.position.x=hero.x;horse.position.z=hero.z;horse.rotation.y=hero.heading;horse.position.y=Math.sin(elapsed*(gallop?15:8))*.06} const d=Math.hypot(hero.x-30,hero.z+62);progress=Math.max(progress,Math.max(0,1-d/95));document.querySelector('#progress').style.width=`${Math.round(progress*100)}%`;document.querySelector('#distance').textContent=`DISTANCE — ${Math.max(0,Math.round(d*5))}m`;const near=Math.hypot(hero.x-4,hero.z+2)<7;document.querySelector('#prompt').textContent=near?'E  INTERACT WITH FRONTIER HORSE':(gallop?'GALLOPING THROUGH THE RED DUST':'WASD / ARROWS TO MOVE');}
function render(){const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;update(dt);const target=new THREE.Vector3(hero.x,2.2,hero.z);const back=new THREE.Vector3(Math.sin(hero.heading)*-9,5.4,Math.cos(hero.heading)*-9);camera.position.lerp(target.clone().add(back),.09);camera.lookAt(target);particles.rotation.y+=dt*.006;fireLight.intensity=7+Math.sin(elapsed*8)*2;renderer.render(scene,camera);requestAnimationFrame(render)}
function start(){playing=true;document.querySelector('#start').classList.add('hidden');toast('The trail begins where the red dust ends.');try{audio=new (window.AudioContext||window.webkitAudioContext)();audio.resume();sfx(110,.5)}catch{muted=true}}
document.querySelector('#start-btn').onclick=start;document.querySelector('#sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)sfx(330,.1)};
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;const down=e=>{e.preventDefault();keys.add(k)};const up=e=>{e.preventDefault();keys.delete(k)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)});
try{render()}catch(err){console.error('Frontier render error',err);window.__frontierError=String(err&&err.stack||err);const f=document.querySelector('#fatal');f.hidden=false;f.style.display='grid';f.querySelector('span').textContent='3D startup failed: '+String(err&&err.message||err).slice(0,120)}
