const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');let W,H,dpr,playing=false,muted=false,t=0,progress=0;const keys=new Set(),r=(a,b)=>a+Math.random()*(b-a);
let hero={x:.5,y:.72,vx:0,vy:0};let horse={x:.67,y:.64};
function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key===' '||e.key.startsWith('Arrow'))e.preventDefault();if(e.key.toLowerCase()==='e'&&playing){progress=Math.min(1,progress+.22);toast(progress>=1?'The letter is found. A new trail opens east.':'The saddle creaks. The frontier is listening.')}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function toast(s){const el=document.querySelector('#toast');el.textContent=s;el.animate([{opacity:0},{opacity:1},{opacity:1},{opacity:0}],{duration:4200});if(!muted)sfx(220,.13,'triangle')}
function sky(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#1d2947');g.addColorStop(.46,'#9c4e3e');g.addColorStop(.68,'#e59a5b');g.addColorStop(1,'#4a2928');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);let sunX=W*.74,sunY=H*.39;ctx.fillStyle='#ffd18a';ctx.shadowColor='#ffbd69';ctx.shadowBlur=45;ctx.beginPath();ctx.arc(sunX,sunY,42,0,7);ctx.fill();ctx.shadowBlur=0}
function mesa(x,y,w,h,c){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x-w*.7,y);ctx.lineTo(x-w*.5,y-h*.66);ctx.lineTo(x-w*.3,y-h);ctx.lineTo(x+w*.38,y-h*.95);ctx.lineTo(x+w*.65,y-h*.62);ctx.lineTo(x+w*.75,y);ctx.closePath();ctx.fill();ctx.fillStyle='#77392f';ctx.fillRect(x-w*.3,y-h*.74,w*.6,4)}
function ground(){ctx.fillStyle='#9a573d';ctx.fillRect(0,H*.63,W,H*.37);ctx.fillStyle='#c1764c';ctx.beginPath();ctx.moveTo(0,H*.68);ctx.quadraticCurveTo(W*.45,H*.55,W,H*.66);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();mesa(W*.12,H*.66,W*.4,H*.24,'#5c3030');mesa(W*.89,H*.68,W*.5,H*.32,'#62302d');mesa(W*.5,H*.65,W*.34,H*.18,'#7a3d32');for(let i=0;i<75;i++){let x=(i*97+t*.015)%W,y=H*.72+(i*43%Math.max(20,H*.23));ctx.fillStyle=i%3?'#75402f':'#e4a060';ctx.fillRect(x,y,1+i%3,1)}}
function town(){let sx=W*.24,sy=H*.65;for(let i=0;i<4;i++){let x=sx+i*W*.075;ctx.fillStyle=i%2?'#6e382d':'#4e2a29';ctx.fillRect(x,sy-48-(i%2)*14,W*.065,48+(i%2)*14);ctx.fillStyle='#2b2025';ctx.beginPath();ctx.moveTo(x-5,sy-48-(i%2)*14);ctx.lineTo(x+W*.032,sy-70-(i%2)*14);ctx.lineTo(x+W*.07,sy-48-(i%2)*14);ctx.fill();ctx.fillStyle='#efb45e';ctx.fillRect(x+W*.025,sy-29,10,17)}ctx.fillStyle='#d49b55';ctx.fillRect(sx-W*.03,sy+3,W*.34,5);ctx.fillStyle='#e9af5b';ctx.font='700 12px Barlow Condensed';ctx.fillText('DUSTHAVEN',sx+W*.08,sy-78)}
function horseDraw(x,y){ctx.save();ctx.translate(x,y);ctx.fillStyle='#392323';ctx.beginPath();ctx.ellipse(0,0,34,17,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(25,-18,14,21,-.25,0,7);ctx.fill();ctx.strokeStyle='#392323';ctx.lineWidth=6;for(let dx of [-20,-7,10,24]){ctx.beginPath();ctx.moveTo(dx,8);ctx.lineTo(dx-3,35);ctx.stroke()}ctx.strokeStyle='#d79a56';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-5,-18);ctx.lineTo(25,-18);ctx.stroke();ctx.restore()}
function rider(){let x=hero.x*W,y=hero.y*H;ctx.save();ctx.translate(x,y);ctx.fillStyle='#201b20';ctx.beginPath();ctx.ellipse(0,15,16,7,0,0,7);ctx.fill();ctx.fillRect(-8,-24,16,38);ctx.fillStyle='#a74932';ctx.beginPath();ctx.arc(0,-31,8,0,7);ctx.fill();ctx.fillStyle='#201617';ctx.fillRect(-14,-40,28,5);ctx.restore()}
function loop(){t++;if(playing){let speed=(keys.has('shift')||keys.has(' '))?.006:.003;let dx=(keys.has('d')||keys.has('arrowright'))-(keys.has('a')||keys.has('arrowleft'));let dy=(keys.has('s')||keys.has('arrowdown'))-(keys.has('w')||keys.has('arrowup'));hero.x=Math.max(.06,Math.min(.94,hero.x+dx*speed));hero.y=Math.max(.59,Math.min(.88,hero.y+dy*speed));if(Math.hypot(hero.x-horse.x,hero.y-horse.y)<.12){document.querySelector('#prompt').textContent='E  INTERACT WITH FRONTIER HORSE'}else document.querySelector('#prompt').textContent='WASD / ARROWS TO MOVE';progress=Math.max(progress,Math.max(0,(hero.y-.72)*-1))}sky();ground();town();horseDraw(horse.x*W,horse.y*H);rider();document.querySelector('#progress').style.width=`${Math.round(progress*100)}%`;document.querySelector('#distance').textContent=`DISTANCE  —  ${Math.max(0,480-Math.round(progress*480))}m`;requestAnimationFrame(loop)}
function sfx(freq,dur,type='sine'){if(muted)return;const ac=window.audioCtx||(window.audioCtx=new AudioContext());const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,ac.currentTime);g.gain.exponentialRampToValueAtTime(.045,ac.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+dur+.02)}
document.querySelector('#start-btn').onclick=()=>{playing=true;document.querySelector('#start').classList.add('hidden');toast('The trail begins where the red dust ends.');sfx(110,.5,'sawtooth')};document.querySelector('#sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)sfx(330,.1)};
